server:
  port: ${APP_PORT:8080}

spring:
  data:
    mongodb:
      host: ${DB_HOST}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      port: ${DB_PORT}
      database: ${DB_NAME}
  