server:
  port: ${APP_PORT:8080}

spring:
  data:
    mongodb:
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      uri: ${DB_URI}
      authentication-database: admin

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
